import Key from './Key.jsx'
const Keyboard = ({ keys }) => {
  return (
    <div>
      <div>
        <Key
          char='q'
          correct={true}
        />
        <Key
          char='w'
          correct={true}
        />
        <Key
          char='e'
          correct={true}
        />
        <Key
          char='r'
          correct={true}
        />
        <Key
          char='t'
          correct={true}
        />
        <Key
          char='y'
          correct={true}
        />
      </div>
      <div>
        <Key
          char='a'
          correct={true}
        />
        <Key
          char='s'
          correct={true}
        />
        <Key
          char='d'
          correct={true}
        />
        <Key
          char='f'
          correct={true}
        />
        <Key
          char='g'
          correct={true}
        />
        <Key
          char='h'
          correct={true}
        />
        <Key
          char='j'
          correct={true}
        />
        <Key
          char='k'
          correct={true}
        />
        <Key
          char='l'
          correct={true}
        />
      </div>
      <div>
        <Key
          char='z'
          correct={true}
        />
        <Key
          char='x'
          correct={true}
        />
        <Key
          char='c'
          correct={true}
        />
        <Key
          char='v'
          correct={true}
        />
        <Key
          char='b'
          correct={true}
        />
        <Key
          char='n'
          correct={true}
        />
        <Key
          char='m'
          correct={true}
        />
      </div>
    </div>
  )
}
export default Keyboard
